spring.application.name=preschool

server.port=${PORT:8080}



spring.datasource.url=jdbc:mysql://localhost:3306/preschool_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false



recaptcha.site-key=6LcquIUsAAAAAJdpCAuCa9GCm8H-okRMP1HjSZwQ
recaptcha.secret-key=6LcquIUsAAAAAAH1glEuTJC_TdOAnu-OjdjhHQNl
